# This workflow will build a Swift project

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mxcl/xcodebuild@v1
    - name: Test JSON output
      run: swift package dump-package
    - name: Show eligible build destinations for SBQuickLook
      run: xcodebuild -showdestinations -scheme SBQuickLook
    - name: Build and test ( iOS 16.0)
      run: xcodebuild test -scheme SBQuickLook -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 12 Pro'


